### ISSUE TITLE
Cookbook needs to be updated for newest version of Seyren

### ISSUE THREAD

**Issue by kjenney** [obazoud/chef-seyren#3]
Seyren 1.1+ wrap Tomcat with Seyren in a jar.

**Comment by obazoud** [comment]
You can configure seyren version via attributes.

**Comment by kjenney** [comment]
What about the war_uri? Should this be updated to reflect the latest jar?

default[:seyren][:war_uri] = 'http://dl.bintray.com/obazoud/generic/seyren-web-1.0.0.war'
